SELECT TRANSACTIONS.T_DATE, EWALLET.EW_PayerProxyName, PROMOCODE.Promo_Code, PRODUCT.Prod_Name, CLASS.C_OpenForGender, CLASSBOOKING.CB_AttendanceStatus, PERSON.P_Name AS EmployeeName, EMPLOYEE.E_EmploymentType
FROM TRANSACTIONS
JOIN EWALLET ON TRANSACTIONS.T_ID = EWALLET.T_ID
JOIN PROMOCODE ON TRANSACTIONS.Promo_ID = PROMOCODE.Promo_ID
JOIN TRANSACTION_PRODUCT ON TRANSACTIONS.T_ID = TRANSACTION_PRODUCT.T_ID
JOIN PRODUCT ON TRANSACTION_PRODUCT.Prod_ID = PRODUCT.Prod_ID
JOIN CLASS ON PRODUCT.Prod_ID = CLASS.Prod_ID
JOIN CLASSBOOKING ON CLASS.C_ID = CLASSBOOKING.C_ID
JOIN PERSON_CLASSBOOKING ON CLASSBOOKING.CB_ID = PERSON_CLASSBOOKING.CB_ID
JOIN PERSON ON PERSON_CLASSBOOKING.P_ID = PERSON.P_ID
JOIN EMPLOYEE ON PERSON.P_ID = EMPLOYEE.P_ID
WHERE TRANSACTIONS.T_Date >= TO_DATE('01/03/2024', 'DD/MM/YYYY')
AND EWALLET.EW_PayerWallet = 'MAE'
AND PROMOCODE.Promo_Status = 'Valid'
AND CLASS.C_CAPACITY > 1
ORDER BY TRANSACTIONS.T_Date DESC;