DROP VIEW EMPLOYEE_SUPPLIER_BRANCH;

CREATE VIEW EMPLOYEE_SUPPLIER_BRANCH 
    AS SELECT EMPLOYEE.E_ID, SUPPLIER.Supp_ID, BRANCH.B_ID 
FROM EMPLOYEE 
JOIN EMPLOYEE_SUPPLIER ON EMPLOYEE.E_ID = EMPLOYEE_SUPPLIER.E_ID 
JOIN SUPPLIER ON EMPLOYEE_SUPPLIER.Supp_ID = SUPPLIER.Supp_ID 
JOIN BRANCH_SUPPLIER ON SUPPLIER.Supp_ID = BRANCH_SUPPLIER.Supp_ID 
JOIN BRANCH ON BRANCH_SUPPLIER.B_ID = BRANCH.B_ID 
WHERE EMPLOYEE.E_YearsOfWorked > 5;

SELECT * FROM EMPLOYEE_SUPPLIER_BRANCH;